version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json"}}
            - v1-dependencies
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - when:
          condition:
              equal: [ dev, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Build dev
                command: |
                    npm run buildDev
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Build prod
                command: |
                    npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_demo:
    working_directory: ~/project
    docker:
      - image: cimg/aws:2023.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: aws --version
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID_DEV
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY_DEV
          region: ${AWS_DEFAULT_REGION_DEV}
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: aws s3 sync dist "s3://moti-inform-web"

  deploy_dev:
    working_directory: ~/project
    docker:
      - image: cimg/aws:2023.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: aws --version
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID_MOTI_DEV
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY_MOTI_DEV
          region: ${AWS_DEFAULT_REGION_MOTI_DEV}
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: aws s3 sync dist "s3://moti-dev-moti-inform-web"
      - run:
          name: Cache Invalidate
          command: aws cloudfront create-invalidation --distribution-id "E302OE8PHKRNZF" --paths "/*";

  deploy_prod:
    working_directory: ~/project
    docker:
      - image: cimg/aws:2023.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: aws --version
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID_MOTI_PROD
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY_MOTI_PROD
          region: ${AWS_DEFAULT_REGION_MOTI_PROD}
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: aws s3 sync dist "s3://moti-prod-moti-inform-web"
      - run:
          name: Cache Invalidate
          command: aws cloudfront create-invalidation --distribution-id "E19SX6R1EBBXKP" --paths "/*";

workflows:
  build_and_deploy_dev:
    when:
      and:
        - equal: [ dev, << pipeline.git.branch >> ]
    jobs:
      - build
      - deploy_demo:
          requires:
            - build
      - deploy_dev:
          requires:
            - build
  build_and_deploy_prod:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
